=== miquik/mkdb/wxclass.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="class">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="classtext" type="xs:string" />
        <xs:element name="function">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:element name="body" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" />
            <xs:attribute name="Parameters" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="Name" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="pythonfile">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="doctext" type="xs:string" />
        <xs:element ref="class" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miquik/mkdb/wxclass.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com) -->
<pythonfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/Miki/Documenti/SharpDevelop%20Projects/testxml/wxclass.xsd">
  <doctext># comment\n</doctext>
  <class Name="BaseFrame">
    <function Name="__init__" Parameters="self, kwd">
      <body>wxFrame.__init(self, -1, "")</body>
    </function>
	<classtext># comment 2\n</classtext>
    <function Name="__set_properties" Parameters="">
      <body>return true</body>
    </function>
  </class>
  <doctext># string</doctext>
  <doctext># string</doctext>
</pythonfile>
