=== miquik/mkdb/wxprops.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com)-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="Property">
    <xs:sequence>
      <xs:element name="Type" type="xs:string" />
      <xs:element name="Category" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element name="InitialValue" type="xs:string" />
      <xs:element name="Browsable" type="xs:boolean" />
      <xs:element name="ReadOnly" type="xs:boolean" />
      <xs:element name="Editor" type="xs:string" />
      <xs:element name="TypeConverter" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="Container">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Properties" type="Property" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" />
      <xs:attribute name="BaseContainer" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miquik/mkdb/wxprops.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com) -->
<Container xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/Michele/Documenti/SharpDevelop%20Projects/mkdb/wxprops.xsd" Name="Conty" BaseContainer="">
  <Properties Name="string">
    <Type>SizeF</Type>
    <Category>String</Category>
    <Description>string</Description>
    <InitialValue>string</InitialValue>
    <Browsable>0</Browsable>
    <ReadOnly>1</ReadOnly>
    <Editor>string</Editor>
    <TypeConverter>string</TypeConverter>
  </Properties>
  <Properties Name="string">
    <Type>string</Type>
    <Category>string</Category>
    <Description>string</Description>
    <InitialValue>string</InitialValue>
    <Browsable>false</Browsable>
    <ReadOnly>0</ReadOnly>
    <Editor>string</Editor>
    <TypeConverter>string</TypeConverter>
  </Properties>
  <Properties Name="string">
    <Type>string</Type>
    <Category>string</Category>
    <Description>string</Description>
    <InitialValue>string</InitialValue>
    <Browsable>0</Browsable>
    <ReadOnly>true</ReadOnly>
    <Editor>string</Editor>
    <TypeConverter>string</TypeConverter>
  </Properties>
  <Properties Name="string">
    <Type>string</Type>
    <Category>string</Category>
    <Description>string</Description>
    <InitialValue>string</InitialValue>
    <Browsable>0</Browsable>
    <ReadOnly>0</ReadOnly>
    <Editor>string</Editor>
    <TypeConverter>string</TypeConverter>
  </Properties>
</Container>
