=== miquik/mkdb/Properties/wxprops.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com)-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="Property">
    <xs:sequence>
      <xs:element name="Type" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Value" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element minOccurs="0" name="Editor" type="xs:string" />
      <xs:element minOccurs="0" name="TypeConverter" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="Catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Category">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Property" type="Property" />
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" />
      <xs:attribute name="Base" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miquik/mkdb/Properties/wxprops.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com) -->
<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/Michele/Documenti/SharpDevelop%20Projects/mkdb/wxprops.xsd" Name="string" Base="string">
  <Category Name="string">
    <Property Name="string">
      <Value>string</Value>
      <Description>string</Description>
      <TypeConverter>string</TypeConverter>
    </Property>
    <Property Name="string">
      <Value>string</Value>
      <Description>string</Description>
      <TypeConverter>string</TypeConverter>
    </Property>
  </Category>
</Catalog>

=== miquik/mkdb/Properties/wxalignment.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com) -->
<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/Michele/Documenti/SharpDevelop%20Projects/mkdb/wxprops.xsd" Name="wxAlignment" Base="">
  <Category Name="Alignment And Borders">
    <Property Name="Proportion">
  	  <Type>int</Type>
      <Value>0</Value>
      <Description>Proportion</Description>
    </Property>
    <Property Name="Border Width">
  	  <Type>int</Type>
      <Value>5</Value>    	
      <Description>Border Width</Description>
    </Property>
    <Property Name="Border Flag">
  	  <Type>wxFlags</Type>
      <Value>wxLEFT,0,false</Value>
      <Value>wxRIGHT,0,false</Value>
      <Value>wxTOP,0,false</Value>
      <Value>wxBOTTOM,0,false</Value>
      <Value>wxALL,0,true</Value>
      <Description>Border Flags</Description>
  	  <Editor>wxFlagsEditor</Editor>
  	  <TypeConverter>wxFlagsTypeConverter</TypeConverter>
    </Property>
  </Category>
</Catalog>
